defaults:
  - model: mistral-7b
  - _self_

seed: 42

push_to_hub: true

hydra:
  run:
    dir: outputs/models/${dataset.name}_${dataset.author_id}_${model.name}
  sweep:
    dir: outputs/models
    subdir: ${dataset.name}_${dataset.author_id}_${model.name}

wandb:
  enabled: false
  project: "uditto"
  name: ${dataset.name}_${dataset.author_id}_${model.name}
  group: "ditto"

lora:
  r: 32
  lora_alpha: 64
  lora_dropout: 0.05
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj

dataset:
  name: ccat50
  name_or_path: "belati/ccat50"
  num_workers: 0

  author_id: 0
  train_samples_per_author: 7
  eval_samples_per_author: 3

training_args:
  general:
    max_grad_norm: 1.0
  sft:
    warmup_steps: 10
    max_steps: 100
    max_length: 1024
    per_device_train_batch_size: 4
  dpo:
    warmup_steps: 10
    max_steps: 40
    max_length: 1024
    gradient_checkpointing: true
    per_device_train_batch_size: 8
    gradient_accumulation_steps: 1
    logging_steps: 1
    beta: 0.05

optim_args:
  sft:
    lr: 1.0e-5 # x10 because of LoRA
    weight_decay: 0
  dpo:
    lr: 1.0e-6 # x10 because of LoRA
    weight_decay: 0

sampler:
  resample_rate: 10
  frac_expert: 0.7
  frac_replay: 0.2
  frac_noisy: 0.1
  rescale_batch: 3

  gen_kwargs:
    do_sample: true
    max_new_tokens: 1024
    num_return_sequences: 10
